[package]
name = "mio-rtmp-server"
version = "0.1.1"
authors = ["Matthew Shapiro <me@mshapiro.net>"]
description = "Simple RTMP server utilizing mio"

[dependencies]
mio = "0.6.13"
slab = "0.4.0"
bytes = "0.4.6"
rml_rtmp = { path = "../../rtmp" }
clap = {version = "2.31", features = ["yaml"]}