[package]
name = "tokio_rtmp_server"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.9", features = ["full"]}
bytes = "1"
rml_rtmp = { path = "../../rtmp" }